export const typeMap: Record<string, string> = {
    BFILE: "string",
    BINARY_DOUBLE: "number",
    BINARY_FLOAT: "number",
    BINARY_INTEGER: "number",
    BLOB: "string",
    "PL/SQL BOOLEAN": "boolean",
    CHAR: "string",
    CLOB: "string",
    SYS_REFCURSOR: "string",
    DATE: "Date",
    FLOAT: "number",
    JSON: "string",
    LONG: "string",
    "LONG RAW": "string",
    NCHAR: "string",
    NCLOB: "string",
    NUMBER: "number",
    NVARCHAR2: "string",
    OBJECT: "string",
    RAW: "string",
    ROWID: "string",
    TIMESTAMP: "Date",
    "TIMESTAMP(6)": "Date",
    "TIMESTAMP WITH LOCAL TIME ZONE": "Date",
    "TIMESTAMP(6) WITH LOCAL TIME ZONE": "Date",
    "TIMESTAMP WITH TIME ZONE": "Date",
    "TIMESTAMP(6) WITH TIME ZONE": "Date",
    VARCHAR2: "string",
    XMLTYPE: "string",
    VECTOR: "string",
};
