export const typeMap: Record<string, string> = {
    BFILE: "string",
    BINARY_DOUBLE: "number",
    BINARY_FLOAT: "number",
    BINARY_INTEGER: "number",
    BLOB: "string",
    "PL/SQL BOOLEAN": "boolean",
    CHAR: "string",
    CLOB: "string",
    SYS_REFCURSOR: "string",
    DATE: "string",
    FLOAT: "number",
    JSON: "string",
    LONG: "string",
    "LONG RAW": "string",
    NCHAR: "string",
    NCLOB: "string",
    NUMBER: "number",
    NVARCHAR2: "string",
    OBJECT: "string",
    RAW: "string",
    ROWID: "string",
    TIMESTAMP: "string",
    "TIMESTAMP WITH LOCAL TIME ZONE": "string",
    "TIMESTAMP WITH TIME ZONE": "string",
    "TIMESTAMP(6)": "string",
    VARCHAR2: "string",
    XMLTYPE: "string",
    VECTOR: "string",
};

export const dateTypes = [
    "DATE",
    "TIMESTAMP",
    "TIMESTAMP WITH LOCAL TIME ZONE",
    "TIMESTAMP WITH TIME ZONE",
    "TIMESTAMP(6)",
];
